### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wjkang** [lowcoding/lowcode-vscode#2]
- [x] schema 支持 [formily](https://github.com/alibaba/formily)
- [x] schema 支持 [amis](https://github.com/baidu/amis)
- [x] 支持 ChatGPT
- [x] 支持 webview 中调用 node.js 脚本
- [x] 生成区块支持 complete 钩子
- [x] 支持本地私有物料
- [ ] 优化代码片段创建页面，更多配置以表单方式配置
- [ ] 优化代码片段编译和生成，可以将更多逻辑放到钩子脚本中，扩大适用范围
- [ ] 支持预置 system prompt
- [ ] 可视化表单的方式编辑更新物料
- [ ] ~~升级 [form-render](https://github.com/alibaba/x-render) 至 2.x~~
- [ ] ~~接入 [rxdrag](https://github.com/codebdy/rxdrag)~~

**Comment by Undertaker-afk** [comment]
Just asking if we can get a english only version
